#ifndef SYSTEM1_COMMON_POSIX_ERRNO_H
#define SYSTEM1_COMMON_POSIX_ERRNO_H

#define POSIX_EPERM   1
#define POSIX_ENOENT  2
#define POSIX_EIO     5
#define POSIX_ENOEXEC 8
#define POSIX_EBADF   9
#define POSIX_EACCES  13
#define POSIX_EEXIST  17
#define POSIX_ENOTDIR 20
#define POSIX_EISDIR  21
#define POSIX_EINVAL  22
#define POSIX_ENOSPC  28
#define POSIX_EROFS   30
#define POSIX_ENOSYS  38

#define POSIX_OK 0

#endif
